site_name: 鱼汤的笔记库
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: 切换暗色
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: 切换亮色
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - 首页: README.md
  - 计算机系统导论: 计算机系统导论/
  - 深度学习: 深度学习/
  - C++学习: C++学习/
  - 人工智能导引: 人工智能导引/
  - 大数据解析和应用导论: 大数据解析和应用导论/
  - 高等代数: 高等代数/
  - 工科数学分析: 工科数学分析/
  - 华中杯: 华中杯/
  - 英语阅读: 英语阅读/
  - 疾病考古学: 疾病考古学/
  - 民族传统体育: 民族传统体育/
  - 通识选修课复习: 通识选修课复习/
  - html学习: html学习/
  - Linux学习: Linux学习/
  - 图灵论坛: 2026_turing/

repo_url: https://github.com/yuyangblue/note
repo_name: GitHub
copyright: © 2025 鱼汤

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: true