site_name: 鱼汤的笔记库
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: 切换暗色
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: 切换亮色
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

repo_url: https://github.com/yuyangblue/note
repo_name: GitHub
copyright: © 2025 鱼汤

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: true